name: Deploy Backend

on:
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment: Prod Space Backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set AWS Region
      run: echo "AWS_DEFAULT_REGION=${{ vars.REGION }}" >> $GITHUB_ENV

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION }}

    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2

    - name: Build SAM application
      run: sam build

    - name: Deploy SAM stack
      run: |
        sam deploy \
          --stack-name ${{ vars.STACK_NAME }} \
          --capabilities CAPABILITY_IAM \
          --region ${{ vars.REGION }} \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset
